</div>
		</section>
		<footer>
			<section class="footer">
				<div class="container" id="footerPadding">
					<h2>101056211</h2>
					<h2>&#169; Nixon Yong Joe Kien</h2>
					<div id="links">
						<a href="mailto:101056211@student.swin.edu.au"><img height="40" width="40" src="../image/email.png" alt="Email Me"/></a>
						<a href="https://www.linkedin.com/in/nixon-yong-803130108"><img height="40" width="40" src="../image/linkedin.png" alt="Phone"/></a>
						<a href="https://facebook.com/nixonyong911"><img height="40" width="40" src="../image/facebook.png" alt="Phone"/></a>
					</div>
				</div>
			</section>
		</footer>
	</body>
</html>
