<form method="post" action="change.php">
	<fieldset><legend>Student ID</legend>
		<p>	<label for="studentID">Student ID: </label>
			<input type="text" name="studentID" id="studentID"/></p>
		<p>	<label for="score">Score: </label>
			<input type="text" name="score" id="score"/></p>
		<p>	
			<input type="submit" value="Change" />
				<a href="../supervisor.html" id="button">Back</a>
		</p>
		
	</fieldset>
</form>