<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="description" content="Assignment 1 reference.html"/>
		<meta name="keywords" content="HTML5, tags"/>
		<meta name="author" content="Nixon Yong Joe Kien, 101056211"/>
		<link href="../styles/supervisor.css" rel="stylesheet"/>
		<title>Supervisor</title>
		<script src="../scripts/supervisor.js"></script>
	</head>
	<body>
		<section class ="navMenu">
			<div class ="container">
				<div class="dropdown">
					<input type="image" src="../image/menu.png" class="menu" width="40" height="40" alt="menu"/>
					<div class="dropdown-content">
						<a href="../index.html">Home</a> 
						<a href="../topic.html">XMLHttpRequest</a> 
						<a href="../reference.html">Reference</a>
						<a href="../enhancement.html">Extra 1</a>
						<a href="../enhancement2.html">Extra 2</a>
						<a href="../enhancement3.html">Extra 3</a>
						<a href="../quiz.html">Quiz</a> 
						<a href="../supervisor.html">Supervisor</a> 
					</div>
				</div>
			</div>
		</section>
		<section class="header">
			<div class="container">
				<h1>Result</h1>
			</div>
		</section>
		<section class="supervisor">
			<div class="container" id="supervisor">
