<form method="post" action="viewOne.php">
	<fieldset><legend>Student ID</legend>
		<p>	<label for="studentID">Student ID: </label>
			<input type="text" name="studentID" id="studentID"/></p>
		<p>	<label for="studentName">Name: </label>
			<input type="text" name="studentName" id="studentName"/></p>
		<p>	
			<input type="submit" value="Search" />
				<a href="../supervisor.html" id="button">Back</a>
		</p>
	</fieldset>
</form>